### ISSUE TITLE
Position err

### ISSUE THREAD

**Issue by gelu-constantin** [c-leitner/Bulk-vCard-QR-Generator#1]
Hi 

On Position description, app generate name from position and add:
SMARTRICS GmbH & Co. KG

Can we change this? 
Can we add other fields?

Thank you

**Comment by c-leitner** [comment]
the issues has been fixed in the latest [release](https://github.com/c-leitner/Bulk-vCard-QR-Generator/releases/tag/v1.0.1). What fields are missing for you? I can add them as long as they are supported by the [vCard v3 standard](https://en.wikipedia.org/wiki/VCard).
